#pragma config(Sensor, in1,    llineFollower,  sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultraIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           motorLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           motorRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  int leftSpeed = 63;
  int rightSpeed = 63;
  SensorValue[encoderRight] = 0;
  SensorValue[encoderLeft] = 0;

  while(true){

    if (SensorValue[encoderRight] > SensorValue[encoderLeft]) {
      leftSpeed++;
      motor[motorLeft] = leftSpeed;
      // rightSpeed--;
      // motor[motorRight] = rightSpeed;
      }

    if (SensorValue[encoderRight] < SensorValue[encoderLeft]) {
      rightSpeed++;
      motor[motorRight] = rightSpeed;
      // leftSpeed--;
      // motor[motorLeft] = leftSpeed;
      }

    if (SensorValue[encoderRight] == SensorValue[encoderLeft]) {
      motor[motorRight] = rightSpeed;
      motor[motorLeft] = leftSpeed;
    }
    if (rightSpeed <0 || rightSpeed > 127) {
      rightSpeed = 63;
    }
    if (leftSpeed < 0 || leftSpeed > 127) {
      leftSpeed = 63;
    }
  }
}
