#pragma config(Sensor, in1,    llineFollower,  sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultraIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           motorLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           motorRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftSpeed = 100;
int rightSpeed = 100;
int Rrpm = 0;
int Lrpm = 0;

task main(){
  SensorValue[encoderRight] = 0;
  SensorValue[encoderLeft] = 0;

  while(true){
    SensorValue[encoderLeft] = 0;
    SensorValue[encoderRight] = 0;
    delay(2000);
    Lrpm = SensorValue[encoderLeft]/2000;
    Rrpm = SensorValue[encoderRight]/2000;
    if(Lrpm > Rrpm)
    {
    	rightSpeed++;
    	motor[motorRight] = rightSpeed;
    	leftSpeed--;
    	motor[motorLeft] = leftSpeed;
    }
    if(Lrpm < Rrpm)
    {
    	leftSpeed++;
    	motor[motorLeft] = leftSpeed;
    	rightSpeed--;
    	motor[motorRight] = rightSpeed;
    }
    if(Lrpm == Rrpm)
    {
      leftSpeed = 100;
    	rightSpeed = 100;
    	motor[motorRight] = rightSpeed;
    	motor[motorLeft] = leftSpeed;
    }
  }
}
