#pragma config(Sensor, in1,    llineFollower,  sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultraIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           motorLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           motorRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variables
int lasTimeLeft = 0, lasTimeRight = 0;
int lasTicksLeft = 0, lasTicksRight = 0;


//Param s: the name of the encoder that you want to get the speed from
//Return: the rotational speed of the shaft being measured by the encoder
// this works by taking the difference in time and dividing the difference in ticks by that time
int getSpeedLeft(int lasTime, int lasTicks){
  int curTime,dT,curTicks, rotSpeed;
  int ticksPerRotation = 360;
  curTime = time1[T1];
  curTicks = SensorValue[encoderLeft];
  dT = curTime-lasTime;
  rotSpeed =  ((curTicks-lasTicks)/ticksPerRotation)/(dT/1000);
  lasTime = curTime;
  lasTicks = curTicks;
  return rotSpeed;
}

int getSpeedRight(int lasTime, int lasTicks){
  int curTime,dT,curTicks, rotSpeed;
  int ticksPerRotation = 360;
  curTime = time1[T2];
  curTicks = SensorValue[encoderRight];
  dT = curTime-lasTime;
  rotSpeed =  ((curTicks-lasTicks)/ticksPerRotation)/(dT/1000);
  lasTime = curTime;
  lasTicks = curTicks;
  return rotSpeed;
}

task main() {
  clearTimer(T1);
  clearTimer(T2);
  int rotSpeedLeft = 0, rotSpeedRight = 0, inputRotSpeed = 3;
  SensorValue[encoderLeft] = 0;
  SensorValue[encoderRight] = 0;
  while(SensorValue[encoderLeft] > 4000){

    rotSpeedLeft = getSpeedLeft(lasTimeLeft,lasTicksLeft);
    rotSpeedRight = getSpeedRight(lasTimeRight,lasTicksRight);

    writeDebugStreamLine("RPM left %d",rotSpeedLeft);
    writeDebugStreamLine("RPM right %d", rotSpeedRight);  

  }

}
